"""
Command-line interface.

    ocpi2sca generate <spec.xml> [--worker <worker.xml>] [-o DIR]
    ocpi2sca validate <dir> <component>
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import emit, validate
from .reader import read_component


def cmd_generate(args: argparse.Namespace) -> int:
    spec = Path(args.spec)
    worker = Path(args.worker) if args.worker else _guess_worker(spec)

    comp = read_component(spec, worker)

    # Inferences are reported before the output, not buried after it: a
    # defaulted type that is wrong produces a descriptor that is confidently
    # incorrect, so the assumption has to be visible.
    for inf in comp.inferences:
        print(f"warning: {inf}", file=sys.stderr)
    for dropped in comp.dropped:
        print(f"warning: dropped -- {dropped}", file=sys.stderr)

    outdir = Path(args.output)
    outdir.mkdir(parents=True, exist_ok=True)

    for filename, content in emit.emit_all(comp, author=args.author).items():
        (outdir / filename).write_bytes(content)
        print(f"wrote {outdir / filename}")

    if not args.no_validate:
        print()
        results = validate.validate_set(outdir, comp.name)
        for r in results:
            print(r)
        if any(not r.ok for r in results):
            return 1

    return 0


def cmd_validate(args: argparse.Namespace) -> int:
    results = validate.validate_set(Path(args.directory), args.component)
    if not results:
        print(f"no descriptors found for {args.component!r} in {args.directory}")
        return 1
    for r in results:
        print(r)
    return 0 if all(r.ok for r in results) else 1


def _guess_worker(spec: Path) -> Path | None:
    """Find the worker descriptor beside the spec, if there is one."""
    stem = spec.stem
    for suffix in ("_spec", "-spec"):
        if stem.lower().endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    candidate = spec.parent / f"{stem}.xml"
    return candidate if candidate.exists() else None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="ocpi2sca",
        description="Generate SCA 2.2.2 descriptors from OpenCPI component metadata.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    g = sub.add_parser("generate", help="generate descriptors from an OpenCPI spec")
    g.add_argument("spec", help="OpenCPI component spec (OCS) XML")
    g.add_argument("--worker", help="OpenCPI worker descriptor (OWD) XML")
    g.add_argument("-o", "--output", default=".", help="output directory")
    g.add_argument("--author", default="Generated by ocpi2sca")
    g.add_argument("--no-validate", action="store_true",
                   help="skip validation after generating")
    g.set_defaults(func=cmd_generate)

    v = sub.add_parser("validate", help="validate an existing descriptor set")
    v.add_argument("directory")
    v.add_argument("component")
    v.set_defaults(func=cmd_validate)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
